version: '2'
services:

  dbt:
    build: .
    volumes:
     - .:/usr/app/
    ports:
      - 8080:8080
    environment:
      - DBT_HOST=rc1b-snvhhm4gp5upjc6t.mdb.yandexcloud.net
      - DBT_USER=admin
      - DBT_PASSWORD=clickhouse
      